import {StyleSheet} from "react-native";
//https://coolors.co/palette/f94144-f3722c-f8961e-f9c74f-90be6d-43aa8b-577590

export const styles = StyleSheet.create({
    darkMode: {
        container: {
            flex: 1,
            backgroundColor: '#1E2124',
            alignItems: 'center',
            justifyContent: 'center',
        },
        contentContainer: {
            flex: 1,
        },
        navbarButtonActive: {
            backgroundColor: '#F9C74F',
            color: '#1E2124',
            padding: 15,
            width: '20%',
            borderRadius: 20,
            textAlign: 'center',
        },
        navbarButton: {
            backgroundColor: '#1E2124',
            color: '#FFFAF0',
            padding: 15,
            width: '20%',
            borderRadius: 15,
            textAlign: 'center',
        },
        navbar: {
            backgroundColor: '#1E2124',
            flexDirection: 'row',
            gap: 30,
            paddingBottom: 10,
            paddingTop: 10,
            borderTopColor: '#577590',
            borderTopWidth: 0.5,
            borderStyle: 'dashed',
            width: '100%',
            justifyContent: 'center',
        },
        map: {
            width: '100%',
            height: '100%',
        },
        itemPriceCategoryOne: {
            backgroundColor: '#2D3136',
            borderStyle: 'solid',
            borderLeftWidth: 15,
            borderLeftColor: '#43AA8B',
            borderWidth: 1,
            borderColor: '#43AA8B',
            padding: 20,
            marginVertical: 8,
            marginHorizontal: 8,
            borderRadius: 15,
        },
        itemPriceCategoryTwo: {
            backgroundColor: '#32363A',
            borderStyle: 'solid',
            borderLeftWidth: 15,
            borderLeftColor: '#90BE6D',
            borderWidth: 1,
            borderColor: '#90BE6D',
            padding: 20,
            marginVertical: 8,
            marginHorizontal: 8,
            borderRadius: 15,
        },
        itemPriceCategoryThree: {
            backgroundColor: '#292C30',
            borderStyle: 'solid',
            borderLeftWidth: 15,
            borderLeftColor: '#F9C74F',
            borderWidth: 1,
            borderColor: '#F9C74F',
            padding: 20,
            marginVertical: 8,
            marginHorizontal: 8,
            borderRadius: 15,
        },
        itemPriceCategoryFour: {
            backgroundColor: '#34383D',
            borderStyle: 'solid',
            borderLeftWidth: 15,
            borderLeftColor: '#F8961E',
            borderWidth: 1,
            borderColor: '#F8961E',
            padding: 20,
            marginVertical: 8,
            marginHorizontal: 8,
            borderRadius: 15,
        },
        itemPriceCategoryFive: {
            backgroundColor: '#363B41',
            borderStyle: 'solid',
            borderLeftWidth: 15,
            borderLeftColor: '#F3722C',
            borderWidth: 1,
            borderColor: '#F3722C',
            padding: 20,
            marginVertical: 8,
            marginHorizontal: 8,
            borderRadius: 15,
        },
        itemPriceCategorySix: {
            backgroundColor: '#34383D',
            borderStyle: 'solid',
            borderLeftWidth: 15,
            borderLeftColor: '#F94144',
            borderWidth: 1,
            borderColor: '#F94144',
            padding: 20,
            marginVertical: 8,
            marginHorizontal: 8,
            borderRadius: 15,
        },
        listItemText: {
            color: '#FFFAF0',
        },
        flatList: {
            width: 350,
        },
        heading: {
            fontSize: 30,
            color: '#FFF',
        },
        picker: {
            color: '#FFF',
        }
    },
    lightMode: {
        container: {
            flex: 1,
            backgroundColor: '#FFF1E3',
            alignItems: 'center',
            justifyContent: 'center',
        },
        contentContainer: {
            flex: 1,
        },
        navbarButtonActive: {
            backgroundColor: '#F9C74F',
            color: '#577590',
            padding: 15,
            width: "20%",
            borderRadius: 20,
            textAlign: 'center',
        },
        navbarButton: {
            backgroundColor: '#577590',
            color: "#FFFAF0",
            padding: 15,
            width: "20%",
            borderRadius: 15,
            textAlign: 'center',
        },
        navbar: {
            backgroundColor: '#fff1f1',
            flexDirection: "row",
            gap: 30,
            paddingBottom: 10,
            paddingTop: 10,
            borderTopColor: '#577590',
            borderTopWidth: .5,
            borderStyle: 'dashed',
            width: '100%',
            justifyContent: "center",
        },
        map: {
            width: '100%',
            height: '100%',
        },
        itemPriceCategoryOne: {
            backgroundColor: '#f7fff9',
            borderStyle: 'solid',
            borderLeftWidth: 15,
            borderLeftColor: '#43AA8B',
            borderWidth: 1,
            borderColor: '#43AA8B',
            padding: 20,
            marginVertical: 8,
            marginHorizontal: 8,
            borderRadius: 15,
        },
        itemPriceCategoryTwo: {
            backgroundColor: '#fdfff8',
            borderStyle: 'solid',
            borderLeftWidth: 15,
            borderLeftColor: '#90BE6D',
            borderWidth: 1,
            borderColor: '#90BE6D',
            padding: 20,
            marginVertical: 8,
            marginHorizontal: 8,
            borderRadius: 15,
        },
        itemPriceCategoryThree: {
            backgroundColor: '#fff3e1',
            borderStyle: 'solid',
            borderLeftWidth: 15,
            borderLeftColor: '#F9C74F',
            borderWidth: 1,
            borderColor: '#F9C74F',
            padding: 20,
            marginVertical: 8,
            marginHorizontal: 8,
            borderRadius: 15,
        },
        itemPriceCategoryFour: {
            backgroundColor: '#ffe9da',
            borderStyle: 'solid',
            borderLeftWidth: 15,
            borderLeftColor: '#F8961E',
            borderWidth: 1,
            borderColor: '#F8961E',
            padding: 20,
            marginVertical: 8,
            marginHorizontal: 8,
            borderRadius: 15,
        },
        itemPriceCategoryFive: {
            backgroundColor: '#ffe7db',
            borderStyle: 'solid',
            borderLeftWidth: 15,
            borderLeftColor: '#F3722C',
            borderWidth: 1,
            borderColor: '#F3722C',
            padding: 20,
            marginVertical: 8,
            marginHorizontal: 8,
            borderRadius: 15,
        },
        itemPriceCategorySix: {
            backgroundColor: '#ffe9e9',
            borderStyle: 'solid',
            borderLeftWidth: 15,
            borderLeftColor: '#F94144',
            borderWidth: 1,
            borderColor: '#F94144',
            padding: 20,
            marginVertical: 8,
            marginHorizontal: 8,
            borderRadius: 15,
        },
        listItemText: {
            color: '#11100d',
        },
        flatList: {
            width: 350
        },
        heading: {
            fontSize: 30
        }
    }

});

